apiVersion: v1
kind: ConfigMap
metadata:
  name: unlock0-config
  labels:
    app.kubernetes.io/name: unlock0
data:
  INSTANCE_DOMAIN: 'api.topia.io'
  INSTANCE_PROTOCOL: 'https'
  INTERACTIVE_KEY: '8ScJzoPWpTfTShNhCgJZ'
  NODE_ENV: 'production'
  PORT: '3000'
